#!/bin/bash
domain=$1
while read sub; do
	if host $sub.$domain $> /dev/null; then
		if [ -s me.txt ]; then
		        while read line; do
		                if ! grep -q $line me.txt; then
		                    echo "$sub.$domain" >> me.txt                      
		                fi
		        done < $out
		    else
		        echo "$sub.$domain" >> me.txt  
		    fi
		fi
done < file.txt
