#!/bin/bash
# copyright 2022 - Black Bug Group
# Author: Edgar Nyandoro - Github: Major2000



PROJDIR="$(dirname "$0")"
cd "${PROJDIR}" || return

# echo "Total arguments : $#"
# echo "1st Argument = $1"
# echo "2nd argument = $2"

# Help function
Help()
{
   # Display Help
   echo

   echo "Looks like you're lost, This HELP Message is enough for the guide!"

   echo

   echo "Syntax: spydomains  -[options:|u|h|o]  [args]"

   echo

   echo "options:"

   echo "           -u     Add the domain you want to brute force for subdomains."

   echo "           -h     Print this Help."

   echo "           -o     Write output to file"

   echo
   
   echo  "Example: spydomain -u example.com -f wordlist.txt -o domains.txt "
  
   echo
}


############################################################
############################################################
# Main program                                             #
############################################################
############################################################

# Set variables
domain="noexample.com"


if [[ -z "$1" || "$#" == 0 ]]; then
    echo
    echo "No option(s)!"
    echo "Try -h or --help option for HELP!"
    echo
    exit


    else

        while getopts ":hu-help:" option; do
            case $option in
                h | -help)
                    Help
                    exit
                    ;;

                u)
                    for i in $@; do
                        echo $i
                        if [$i == -u]; then
                            domain=$opt
                        fi
                    done
                    echo $domain
                    ;;
                *)
                    echo
                    echo "Invalid option(s)!"
                    echo "Try -h or --help option for HELP!"
                    echo
                    exit
                    ;;
            esac
        done
        shift $(($OPTIND -1))
fi