#!/bin/bash
# copyright 2022 - Black Bug Group
# Author: Edgar Nyandoro - Github: Major2000



PROJDIR="$(dirname "$0")"
cd "${PROJDIR}" || return

# echo "Total arguments : $#"
# echo "1st Argument = $1"
# echo "2nd argument = $2"

# Help function
Help()
{
   # Display Help
   echo

   echo "Looks like you're lost, This HELP Message is enough for the guide!"

   echo

   echo "Syntax: spydomains  -[options:|u, U|f, F|o, O|h, H]  [args]"

   echo

   echo "options:"

   echo "           -u, -U     Add the domain you want to brute force for subdomains."

   echo "           -f, -F     Add a custome brute-force world list of domains"

   echo "           -o, -O     Print to  external file"

   echo "           -h, -H     Print this Help."

   echo
   
   echo  "Example: spydomains -u example.com -f wordlist.txt -o domains.txt  - With word list"

   echo  "Example: spydomains -u example.com - without word list"
  
   echo
}


############################################################
############################################################
# Main program                                             #
############################################################
############################################################

# Set variables
domain=""
pos=0
file=



###### Check and capture the arguments
if [[ -z "$1" || "$#" == 0 ]]; then
    echo
    echo "No option(s)!"
    echo "Try -h option for HELP!"
    exit


    else

        while getopts "hHu:U:o:O:" option; do
            case $option in
                h | H)
                    Help
                    exit
                    ;;

                u | U)
                    for i in $@; do
                        let "pos++"
                        # echo $i
                        # echo $#
                        if [[ $i == "-u" || $i == "-U" ]]; then
                            let "pos++"
                            case $pos in
                                2) domain=$2;;
                                3) domain=$3;;
                                4) domain=$4;;
                                5) domain=$5;;
                                6) domain=$6;;
                            esac
                        fi
                    done
                    ;;

                *)
                    echo
                    echo "Invalid option(s)!"
                    echo "Try -h option for HELP!"
                    exit
                    ;;
            esac
        done
        # shift $(($OPTIND -1))
fi




##### Reccon starts here!
# echo $domain
while read sub; do 
    if host "$sub.$domain" &> /dev/null; then
        echo "$sub.$domain"
    fi
done