#!/bin/bash
# copyright 2022 - Black Bug Group
# Author: Edgar Nyandoro - Github: Major2000

PROJDIR="$(dirname "$0")"
cd "${PROJDIR}" || return

# wordlist=$1



# echo "Total arguments : $#"
# echo "1st Argument = $0"
# echo "2nd argument = $2"



# Help function
Help()

{

   # Display Help
   echo

   echo "Looks like you're lost, This HELP Message is enough for the guide!"

   echo

   echo "Syntax: spydomains  -[options:|u|h|o]  [args]"

   echo

   echo "options:"

   echo "           -u     Add the domain you want to brute force for subdomains."

   echo "           -h     Print this Help."

   echo "           -o     Write output to file"

   echo
   
   echo  "Example: spydomain -u example.com -f wordlist.txt -o domains.txt "
  
   echo

}


if [[ -z "$1" || "$#" == 0 ]]; then
    echo "Try -h or --help option for HELP!"
    exit


    else
        for args in "$@"; do
            case $args in
                -h | --help)
                    Help
                    exit
                    ;;
                
                -u) domain="$OPTARG"
                    # if [ host "$domain" ]; then
                    #     echo "It resolves!"
                    # fi
                    echo "$domain"
                    shift
                    ;;
            esac
        done
fi 